
# options for phone
# ANDROID_TOOLCHAIN=arm64
# ANDROID_ARCH=arm64-v8a

ANDROID_TOOLCHAIN=x86_64
ANDROID_ARCH=x86_64
ANDROID_CONFIGURATION=debug
CURRENT_DIR=$(pwd)
IB_CONFIG="android_${ANDROID_TOOLCHAIN}_${ANDROID_ARCH}_${ANDROID_CONFIGURATION}"
IB_TARGET=jni/libnative-activity
mkdir -p ../out/${IB_CONFIG}/${IB_TARGET}
IB_OUTPUT=../out/${IB_CONFIG}/${IB_TARGET}
IB_OUTDIR=$(dirname $IB_OUTPUT)
ANDROID_TOOLCHAIN_DIR=${IB_OUTDIR}/native-toolchain-${ANDROID_TOOLCHAIN}
